namespace Roomed.Common
{
    using Microsoft.AspNetCore.Mvc.Rendering;

    /// <summary>
    /// This static class contains all common global constants.
    /// </summary>
    public static class GlobalConstants
    {
        public const string CopyrightText = "Copyright © Roomed 2022";

        public static readonly HashSet<string> Nationalities = new HashSet<string>()
        {
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia (Plurinational State of)",
            "Bonaire, Sint Eustatius and Saba",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Democratic Republic Congo",
            "Congo",
            "Cook Islands",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czechia",
            "Côte d'Ivoire",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Faroe Islands",
            "Faroe",
            "Fiji",
            "Finland",
            "France",
            "French Polynesia",
            "French",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard Island and McDonald Islands",
            "Holy See",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea Democratic People's Republic",
            "Korea Republic",
            "Kuwait",
            "Kyrgyzstan",
            "Lao People's Democratic Republic",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia Federated States",
            "Moldova Republic",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine,",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Republic of North Macedonia",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Réunion",
            "Saint Barthélemy",
            "Saint Helena, Ascension and Tristan da Cunha",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (French part)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten (Dutch part)",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan (Province of China)",
            "Tajikistan",
            "Tanzania, United Republic",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom of Great Britain and Northern Ireland",
            "United States Minor Outlying Islands",
            "United States of America",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Viet Nam",
            "Virgin Islands (British)",
            "Virgin Islands (U.S.)",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe",
            "Åland Islands",
        };

        public static readonly HashSet<string> NationalityCodes = new HashSet<string>()
        {
            "AF",
            "AL",
            "DZ",
            "AS",
            "AD",
            "AO",
            "AI",
            "AQ",
            "AB",
            "AR",
            "AM",
            "AW",
            "AU",
            "AT",
            "AZ",
            "BS",
            "BH",
            "BD",
            "BB",
            "BY",
            "BE",
            "BZ",
            "BJ",
            "BM",
            "BT",
            "BO",
            "BQ",
            "BA",
            "BW",
            "BV",
            "BR",
            "IO",
            "BN",
            "BG",
            "BF",
            "BI",
            "CV",
            "KH",
            "CM",
            "CA",
            "KY",
            "CF",
            "TD",
            "CL",
            "CN",
            "CX",
            "CC",
            "CO",
            "KM",
            "CD",
            "CG",
            "CK",
            "CR",
            "HR",
            "CU",
            "CW",
            "CY",
            "CZ",
            "CI",
            "DK",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "EE",
            "SZ",
            "ET",
            "FK",
            "FO",
            "FJ",
            "FI",
            "FR",
            "GF",
            "PF",
            "TF",
            "GA",
            "GM",
            "GE",
            "DE",
            "GH",
            "GI",
            "GR",
            "GL",
            "GD",
            "GP",
            "GU",
            "GT",
            "GG",
            "GN",
            "GW",
            "GY",
            "HT",
            "HM",
            "VA",
            "HN",
            "HK",
            "HU",
            "IS",
            "IN",
            "ID",
            "IR",
            "IQ",
            "IE",
            "IM",
            "IL",
            "IT",
            "JM",
            "JP",
            "JE",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KP",
            "KR",
            "KW",
            "KG",
            "LA",
            "LV",
            "LB",
            "LS",
            "LR",
            "LY",
            "LI",
            "LT",
            "LU",
            "MO",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MT",
            "MH",
            "MQ",
            "MR",
            "MU",
            "YT",
            "MX",
            "FM",
            "MD",
            "MC",
            "MN",
            "ME",
            "MS",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NL",
            "NC",
            "NZ",
            "NI",
            "NE",
            "NG",
            "NU",
            "NF",
            "MP",
            "NO",
            "OM",
            "PK",
            "PW",
            "PS",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "PN",
            "PL",
            "PT",
            "PR",
            "QA",
            "MK",
            "RO",
            "RU",
            "RW",
            "RE",
            "BL",
            "SH",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "WS",
            "SM",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SX",
            "SK",
            "SI",
            "SB",
            "SO",
            "ZA",
            "GS",
            "SS",
            "ES",
            "LK",
            "SD",
            "SR",
            "SJ",
            "SE",
            "CH",
            "SY",
            "TW",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TK",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TC",
            "TV",
            "UG",
            "UA",
            "AE",
            "GB",
            "UM",
            "US",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "VG",
            "VI",
            "WF",
            "EH",
            "YE",
            "ZM",
            "ZW",
            "AX",
        };

        public static readonly Dictionary<string, string> NationalitiesDictionary =
            Nationality_Code_SelectList().ToDictionary(sl => sl.Value, sl => sl.Text);

        public static List<SelectListItem> NationalitiesSelectList()
        {
            return Nationalities.Select(n => new SelectListItem() { Value = n, Text = n }).ToList();
        }

        public static List<SelectListItem> NationalityCodesSelectList()
        {
            return NationalityCodes.Select(nc => new SelectListItem() { Value = nc, Text = nc }).ToList();
        }

        public static List<SelectListItem> Code_Nationality_SelectList()
        {
            var selectList = new List<SelectListItem>();

            var nationalitiesEnumerator = Nationalities.GetEnumerator();
            var nationalityCodesEnumerator = NationalityCodes.GetEnumerator();

            while (nationalitiesEnumerator.MoveNext() && nationalityCodesEnumerator.MoveNext())
            {
                string nationality = nationalitiesEnumerator.Current;
                string nationalyCode = nationalityCodesEnumerator.Current;

                selectList.Add(new SelectListItem() { Value = nationalyCode, Text = nationality });
            }

            return selectList;
        }

        public static List<SelectListItem> Nationality_Code_SelectList()
        {
            var selectList = new List<SelectListItem>();

            var nationalitiesEnumerator = Nationalities.GetEnumerator();
            var nationalityCodesEnumerator = NationalityCodes.GetEnumerator();

            while (nationalitiesEnumerator.MoveNext() && nationalityCodesEnumerator.MoveNext())
            {
                string nationality = nationalitiesEnumerator.Current;
                string nationalyCode = nationalityCodesEnumerator.Current;

                selectList.Add(new SelectListItem() { Value = nationality, Text = nationalyCode });
            }

            return selectList;
        }

        public static readonly List<SelectListItem> DocumentTypes = new List<SelectListItem>()
        {
            new SelectListItem() { Value = "0", Text = "Id" },
            new SelectListItem() { Value = "1", Text = "Passport" },
            new SelectListItem() { Value = "2", Text = "Driving license" },
        };

        public static readonly List<SelectListItem> Genders = new List<SelectListItem>()
        {
            new SelectListItem() { Value = "0", Text = "Male" },
            new SelectListItem() { Value = "1", Text = "Female" },
        };

        //public static readonly List<SelectListItem> Code_Nationality = new List<SelectListItem>()
        //{
        //    new SelectListItem() { Value = "AF", Text = "Afghanistan" },
        //    new SelectListItem() { Value = "AL", Text = "Albania" },
        //    new SelectListItem() { Value = "DZ", Text = "Algeria" },
        //    new SelectListItem() { Value = "AS", Text = "American Samoa" },
        //    new SelectListItem() { Value = "AD", Text = "Andorra" },
        //    new SelectListItem() { Value = "AO", Text = "Angola" },
        //    new SelectListItem() { Value = "AI", Text = "Anguilla" },
        //    new SelectListItem() { Value = "AQ", Text = "Antarctica" },
        //    new SelectListItem() { Value = "AB", Text = "Antigua and Barbuda" },
        //    new SelectListItem() { Value = "AR", Text = "Argentina" },
        //    new SelectListItem() { Value = "AM", Text = "Armenia" },
        //    new SelectListItem() { Value = "AW", Text = "Aruba" },
        //    new SelectListItem() { Value = "AU", Text = "Australia" },
        //    new SelectListItem() { Value = "AT", Text = "Austria" },
        //    new SelectListItem() { Value = "AZ", Text = "Azerbaijan" },
        //    new SelectListItem() { Value = "BS", Text = "Bahamas" },
        //    new SelectListItem() { Value = "BH", Text = "Bahrain" },
        //    new SelectListItem() { Value = "BD", Text = "Bangladesh" },
        //    new SelectListItem() { Value = "BB", Text = "Barbados" },
        //    new SelectListItem() { Value = "BY", Text = "Belarus" },
        //    new SelectListItem() { Value = "BE", Text = "Belgium" },
        //    new SelectListItem() { Value = "BZ", Text = "Belize" },
        //    new SelectListItem() { Value = "BJ", Text = "Benin" },
        //    new SelectListItem() { Value = "BM", Text = "Bermuda" },
        //    new SelectListItem() { Value = "BT", Text = "Bhutan" },
        //    new SelectListItem() { Value = "BO", Text = "Bolivia (Plurinational State of)" },
        //    new SelectListItem() { Value = "BQ", Text = "Bonaire, Sint Eustatius and Saba" },
        //    new SelectListItem() { Value = "BA", Text = "Bosnia and Herzegovina" },
        //    new SelectListItem() { Value = "BW", Text = "Botswana" },
        //    new SelectListItem() { Value = "BV", Text = "Bouvet Island" },
        //    new SelectListItem() { Value = "BR", Text = "Brazil" },
        //    new SelectListItem() { Value = "IO", Text = "British Indian Ocean Territory" },
        //    new SelectListItem() { Value = "BN", Text = "Brunei Darussalam" },
        //    new SelectListItem() { Value = "BG", Text = "Bulgaria" },
        //    new SelectListItem() { Value = "BF", Text = "Burkina Faso" },
        //    new SelectListItem() { Value = "BI", Text = "Burundi" },
        //    new SelectListItem() { Value = "CV", Text = "Cabo Verde" },
        //    new SelectListItem() { Value = "KH", Text = "Cambodia" },
        //    new SelectListItem() { Value = "CM", Text = "Cameroon" },
        //    new SelectListItem() { Value = "CA", Text = "Canada" },
        //    new SelectListItem() { Value = "KY", Text = "Cayman Islands" },
        //    new SelectListItem() { Value = "CF", Text = "Central African Republic" },
        //    new SelectListItem() { Value = "TD", Text = "Chad" },
        //    new SelectListItem() { Value = "CL", Text = "Chile" },
        //    new SelectListItem() { Value = "CN", Text = "China" },
        //    new SelectListItem() { Value = "CX", Text = "Christmas Island" },
        //    new SelectListItem() { Value = "CC", Text = "Cocos (Keeling) Islands" },
        //    new SelectListItem() { Value = "CO", Text = "Colombia" },
        //    new SelectListItem() { Value = "KM", Text = "Comoros" },
        //    new SelectListItem() { Value = "CD", Text = "Democratic Republic Congo" },
        //    new SelectListItem() { Value = "CG", Text = "Congo" },
        //    new SelectListItem() { Value = "CK", Text = "Cook Islands" },
        //    new SelectListItem() { Value = "CR", Text = "Costa Rica" },
        //    new SelectListItem() { Value = "HR", Text = "Croatia" },
        //    new SelectListItem() { Value = "CU", Text = "Cuba" },
        //    new SelectListItem() { Value = "CW", Text = "Curaçao" },
        //    new SelectListItem() { Value = "CY", Text = "Cyprus" },
        //    new SelectListItem() { Value = "CZ", Text = "Czechia" },
        //    new SelectListItem() { Value = "CI", Text = "Côte d'Ivoire" },
        //    new SelectListItem() { Value = "DK", Text = "Denmark" },
        //    new SelectListItem() { Value = "DJ", Text = "Djibouti" },
        //    new SelectListItem() { Value = "DM", Text = "Dominica" },
        //    new SelectListItem() { Value = "DO", Text = "Dominican Republic" },
        //    new SelectListItem() { Value = "EC", Text = "Ecuador" },
        //    new SelectListItem() { Value = "EG", Text = "Egypt" },
        //    new SelectListItem() { Value = "SV", Text = "El Salvador" },
        //    new SelectListItem() { Value = "GQ", Text = "Equatorial Guinea" },
        //    new SelectListItem() { Value = "ER", Text = "Eritrea" },
        //    new SelectListItem() { Value = "EE", Text = "Estonia" },
        //    new SelectListItem() { Value = "SZ", Text = "Eswatini" },
        //    new SelectListItem() { Value = "ET", Text = "Ethiopia" },
        //    new SelectListItem() { Value = "FK", Text = "Faroe Islands" },
        //    new SelectListItem() { Value = "FO", Text = "Faroe" },
        //    new SelectListItem() { Value = "FJ", Text = "Fiji" },
        //    new SelectListItem() { Value = "FI", Text = "Finland" },
        //    new SelectListItem() { Value = "FR", Text = "France" },
        //    new SelectListItem() { Value = "GF", Text = "French Polynesia" },
        //    new SelectListItem() { Value = "PF", Text = "French" },
        //    new SelectListItem() { Value = "TF", Text = "French Southern Territories" },
        //    new SelectListItem() { Value = "GA", Text = "Gabon" },
        //    new SelectListItem() { Value = "GM", Text = "Gambia" },
        //    new SelectListItem() { Value = "GE", Text = "Georgia" },
        //    new SelectListItem() { Value = "DE", Text = "Germany" },
        //    new SelectListItem() { Value = "GH", Text = "Ghana" },
        //    new SelectListItem() { Value = "GI", Text = "Gibraltar" },
        //    new SelectListItem() { Value = "GR", Text = "Greece" },
        //    new SelectListItem() { Value = "GL", Text = "Greenland" },
        //    new SelectListItem() { Value = "GD", Text = "Grenada" },
        //    new SelectListItem() { Value = "GP", Text = "Guadeloupe" },
        //    new SelectListItem() { Value = "GU", Text = "Guam" },
        //    new SelectListItem() { Value = "GT", Text = "Guatemala" },
        //    new SelectListItem() { Value = "GG", Text = "Guernsey" },
        //    new SelectListItem() { Value = "GN", Text = "Guinea" },
        //    new SelectListItem() { Value = "GW", Text = "Guinea-Bissau" },
        //    new SelectListItem() { Value = "GY", Text = "Guyana" },
        //    new SelectListItem() { Value = "HT", Text = "Haiti" },
        //    new SelectListItem() { Value = "HM", Text = "Heard Island and McDonald Islands" },
        //    new SelectListItem() { Value = "VA", Text = "Holy See" },
        //    new SelectListItem() { Value = "HN", Text = "Honduras" },
        //    new SelectListItem() { Value = "HK", Text = "Hong Kong" },
        //    new SelectListItem() { Value = "HU", Text = "Hungary" },
        //    new SelectListItem() { Value = "IS", Text = "Iceland" },
        //    new SelectListItem() { Value = "IN", Text = "India" },
        //    new SelectListItem() { Value = "ID", Text = "Indonesia" },
        //    new SelectListItem() { Value = "IR", Text = "Iran" },
        //    new SelectListItem() { Value = "IQ", Text = "Iraq" },
        //    new SelectListItem() { Value = "IE", Text = "Ireland" },
        //    new SelectListItem() { Value = "IM", Text = "Isle of Man" },
        //    new SelectListItem() { Value = "IL", Text = "Israel" },
        //    new SelectListItem() { Value = "IT", Text = "Italy" },
        //    new SelectListItem() { Value = "JM", Text = "Jamaica" },
        //    new SelectListItem() { Value = "JP", Text = "Japan" },
        //    new SelectListItem() { Value = "JE", Text = "Jersey" },
        //    new SelectListItem() { Value = "JO", Text = "Jordan" },
        //    new SelectListItem() { Value = "KZ", Text = "Kazakhstan" },
        //    new SelectListItem() { Value = "KE", Text = "Kenya" },
        //    new SelectListItem() { Value = "KI", Text = "Kiribati" },
        //    new SelectListItem() { Value = "KP", Text = "Korea Democratic People's Republic" },
        //    new SelectListItem() { Value = "KR", Text = "Korea Republic" },
        //    new SelectListItem() { Value = "KW", Text = "Kuwait" },
        //    new SelectListItem() { Value = "KG", Text = "Kyrgyzstan" },
        //    new SelectListItem() { Value = "LA", Text = "Lao People's Democratic Republic" },
        //    new SelectListItem() { Value = "LV", Text = "Latvia" },
        //    new SelectListItem() { Value = "LB", Text = "Lebanon" },
        //    new SelectListItem() { Value = "LS", Text = "Lesotho" },
        //    new SelectListItem() { Value = "LR", Text = "Liberia" },
        //    new SelectListItem() { Value = "LY", Text = "Libya" },
        //    new SelectListItem() { Value = "LI", Text = "Liechtenstein" },
        //    new SelectListItem() { Value = "LT", Text = "Lithuania" },
        //    new SelectListItem() { Value = "LU", Text = "Luxembourg" },
        //    new SelectListItem() { Value = "MO", Text = "Macao" },
        //    new SelectListItem() { Value = "MG", Text = "Madagascar" },
        //    new SelectListItem() { Value = "MW", Text = "Malawi" },
        //    new SelectListItem() { Value = "MY", Text = "Malaysia" },
        //    new SelectListItem() { Value = "MV", Text = "Maldives" },
        //    new SelectListItem() { Value = "ML", Text = "Mali" },
        //    new SelectListItem() { Value = "MT", Text = "Malta" },
        //    new SelectListItem() { Value = "MH", Text = "Marshall Islands" },
        //    new SelectListItem() { Value = "MQ", Text = "Martinique" },
        //    new SelectListItem() { Value = "MR", Text = "Mauritania" },
        //    new SelectListItem() { Value = "MU", Text = "Mauritius" },
        //    new SelectListItem() { Value = "YT", Text = "Mayotte" },
        //    new SelectListItem() { Value = "MX", Text = "Mexico" },
        //    new SelectListItem() { Value = "FM", Text = "Micronesia Federated States" },
        //    new SelectListItem() { Value = "MD", Text = "Moldova Republic" },
        //    new SelectListItem() { Value = "MC", Text = "Monaco" },
        //    new SelectListItem() { Value = "MN", Text = "Mongolia" },
        //    new SelectListItem() { Value = "ME", Text = "Montenegro" },
        //    new SelectListItem() { Value = "MS", Text = "Montserrat" },
        //    new SelectListItem() { Value = "MA", Text = "Morocco" },
        //    new SelectListItem() { Value = "MZ", Text = "Mozambique" },
        //    new SelectListItem() { Value = "MM", Text = "Myanmar" },
        //    new SelectListItem() { Value = "NA", Text = "Namibia" },
        //    new SelectListItem() { Value = "NR", Text = "Nauru" },
        //    new SelectListItem() { Value = "NP", Text = "Nepal" },
        //    new SelectListItem() { Value = "NL", Text = "Netherlands" },
        //    new SelectListItem() { Value = "NC", Text = "New Caledonia" },
        //    new SelectListItem() { Value = "NZ", Text = "New Zealand" },
        //    new SelectListItem() { Value = "NI", Text = "Nicaragua" },
        //    new SelectListItem() { Value = "NE", Text = "Niger" },
        //    new SelectListItem() { Value = "NG", Text = "Nigeria" },
        //    new SelectListItem() { Value = "NU", Text = "Niue" },
        //    new SelectListItem() { Value = "NF", Text = "Norfolk Island" },
        //    new SelectListItem() { Value = "MP", Text = "Northern Mariana Islands" },
        //    new SelectListItem() { Value = "NO", Text = "Norway" },
        //    new SelectListItem() { Value = "OM", Text = "Oman" },
        //    new SelectListItem() { Value = "PK", Text = "Pakistan" },
        //    new SelectListItem() { Value = "PW", Text = "Palau" },
        //    new SelectListItem() { Value = "PS", Text = "Palestine," },
        //    new SelectListItem() { Value = "PA", Text = "Panama" },
        //    new SelectListItem() { Value = "PG", Text = "Papua New Guinea" },
        //    new SelectListItem() { Value = "PY", Text = "Paraguay" },
        //    new SelectListItem() { Value = "PE", Text = "Peru" },
        //    new SelectListItem() { Value = "PH", Text = "Philippines" },
        //    new SelectListItem() { Value = "PN", Text = "Pitcairn" },
        //    new SelectListItem() { Value = "PL", Text = "Poland" },
        //    new SelectListItem() { Value = "PT", Text = "Portugal" },
        //    new SelectListItem() { Value = "PR", Text = "Puerto Rico" },
        //    new SelectListItem() { Value = "QA", Text = "Qatar" },
        //    new SelectListItem() { Value = "MK", Text = "Republic of North Macedonia" },
        //    new SelectListItem() { Value = "RO", Text = "Romania" },
        //    new SelectListItem() { Value = "RU", Text = "Russian Federation" },
        //    new SelectListItem() { Value = "RW", Text = "Rwanda" },
        //    new SelectListItem() { Value = "RE", Text = "Réunion" },
        //    new SelectListItem() { Value = "BL", Text = "Saint Barthélemy" },
        //    new SelectListItem() { Value = "SH", Text = "Saint Helena, Ascension and Tristan da Cunha" },
        //    new SelectListItem() { Value = "KN", Text = "Saint Kitts and Nevis" },
        //    new SelectListItem() { Value = "LC", Text = "Saint Lucia" },
        //    new SelectListItem() { Value = "MF", Text = "Saint Martin (French part)" },
        //    new SelectListItem() { Value = "PM", Text = "Saint Pierre and Miquelon" },
        //    new SelectListItem() { Value = "VC", Text = "Saint Vincent and the Grenadines" },
        //    new SelectListItem() { Value = "WS", Text = "Samoa" },
        //    new SelectListItem() { Value = "SM", Text = "San Marino" },
        //    new SelectListItem() { Value = "ST", Text = "Sao Tome and Principe" },
        //    new SelectListItem() { Value = "SA", Text = "Saudi Arabia" },
        //    new SelectListItem() { Value = "SN", Text = "Senegal" },
        //    new SelectListItem() { Value = "RS", Text = "Serbia" },
        //    new SelectListItem() { Value = "SC", Text = "Seychelles" },
        //    new SelectListItem() { Value = "SL", Text = "Sierra Leone" },
        //    new SelectListItem() { Value = "SG", Text = "Singapore" },
        //    new SelectListItem() { Value = "SX", Text = "Sint Maarten (Dutch part)" },
        //    new SelectListItem() { Value = "SK", Text = "Slovakia" },
        //    new SelectListItem() { Value = "SI", Text = "Slovenia" },
        //    new SelectListItem() { Value = "SB", Text = "Solomon Islands" },
        //    new SelectListItem() { Value = "SO", Text = "Somalia" },
        //    new SelectListItem() { Value = "ZA", Text = "South Africa" },
        //    new SelectListItem() { Value = "GS", Text = "South Georgia and the South Sandwich Islands" },
        //    new SelectListItem() { Value = "SS", Text = "South Sudan" },
        //    new SelectListItem() { Value = "ES", Text = "Spain" },
        //    new SelectListItem() { Value = "LK", Text = "Sri Lanka" },
        //    new SelectListItem() { Value = "SD", Text = "Sudan" },
        //    new SelectListItem() { Value = "SR", Text = "Suriname" },
        //    new SelectListItem() { Value = "SJ", Text = "Svalbard and Jan Mayen" },
        //    new SelectListItem() { Value = "SE", Text = "Sweden" },
        //    new SelectListItem() { Value = "CH", Text = "Switzerland" },
        //    new SelectListItem() { Value = "SY", Text = "Syrian Arab Republic" },
        //    new SelectListItem() { Value = "TW", Text = "Taiwan (Province of China)" },
        //    new SelectListItem() { Value = "TJ", Text = "Tajikistan" },
        //    new SelectListItem() { Value = "TZ", Text = "Tanzania, United Republic" },
        //    new SelectListItem() { Value = "TH", Text = "Thailand" },
        //    new SelectListItem() { Value = "TL", Text = "Timor-Leste" },
        //    new SelectListItem() { Value = "TG", Text = "Togo" },
        //    new SelectListItem() { Value = "TK", Text = "Tokelau" },
        //    new SelectListItem() { Value = "TO", Text = "Tonga" },
        //    new SelectListItem() { Value = "TT", Text = "Trinidad and Tobago" },
        //    new SelectListItem() { Value = "TN", Text = "Tunisia" },
        //    new SelectListItem() { Value = "TR", Text = "Turkey" },
        //    new SelectListItem() { Value = "TM", Text = "Turkmenistan" },
        //    new SelectListItem() { Value = "TC", Text = "Turks and Caicos Islands" },
        //    new SelectListItem() { Value = "TV", Text = "Tuvalu" },
        //    new SelectListItem() { Value = "UG", Text = "Uganda" },
        //    new SelectListItem() { Value = "UA", Text = "Ukraine" },
        //    new SelectListItem() { Value = "AE", Text = "United Arab Emirates" },
        //    new SelectListItem() { Value = "GB", Text = "United Kingdom of Great Britain and Northern Ireland" },
        //    new SelectListItem() { Value = "UM", Text = "United States Minor Outlying Islands" },
        //    new SelectListItem() { Value = "US", Text = "United States of America" },
        //    new SelectListItem() { Value = "UY", Text = "Uruguay" },
        //    new SelectListItem() { Value = "UZ", Text = "Uzbekistan" },
        //    new SelectListItem() { Value = "VU", Text = "Vanuatu" },
        //    new SelectListItem() { Value = "VE", Text = "Venezuela" },
        //    new SelectListItem() { Value = "VN", Text = "Viet Nam" },
        //    new SelectListItem() { Value = "VG", Text = "Virgin Islands (British)" },
        //    new SelectListItem() { Value = "VI", Text = "Virgin Islands (U.S.)" },
        //    new SelectListItem() { Value = "WF", Text = "Wallis and Futuna" },
        //    new SelectListItem() { Value = "EH", Text = "Western Sahara" },
        //    new SelectListItem() { Value = "YE", Text = "Yemen" },
        //    new SelectListItem() { Value = "ZM", Text = "Zambia" },
        //    new SelectListItem() { Value = "ZW", Text = "Zimbabwe" },
        //    new SelectListItem() { Value = "AX", Text = "Åland Islands" },
        //};

        //public static readonly List<SelectListItem> NationalityCodes = new List<SelectListItem>
        //{
        //    new SelectListItem() { Value = "AF", Text = "AF" },
        //    new SelectListItem() { Value = "AL", Text = "AL" },
        //    new SelectListItem() { Value = "DZ", Text = "DZ" },
        //    new SelectListItem() { Value = "AS", Text = "AS" },
        //    new SelectListItem() { Value = "AD", Text = "AD" },
        //    new SelectListItem() { Value = "AO", Text = "AO" },
        //    new SelectListItem() { Value = "AI", Text = "AI" },
        //    new SelectListItem() { Value = "AQ", Text = "AQ" },
        //    new SelectListItem() { Value = "AB", Text = "AB" },
        //    new SelectListItem() { Value = "AR", Text = "AR" },
        //    new SelectListItem() { Value = "AM", Text = "AM" },
        //    new SelectListItem() { Value = "AW", Text = "AW" },
        //    new SelectListItem() { Value = "AU", Text = "AU" },
        //    new SelectListItem() { Value = "AT", Text = "AT" },
        //    new SelectListItem() { Value = "AZ", Text = "AZ" },
        //    new SelectListItem() { Value = "BS", Text = "BS" },
        //    new SelectListItem() { Value = "BH", Text = "BH" },
        //    new SelectListItem() { Value = "BD", Text = "BD" },
        //    new SelectListItem() { Value = "BB", Text = "BB" },
        //    new SelectListItem() { Value = "BY", Text = "BY" },
        //    new SelectListItem() { Value = "BE", Text = "BE" },
        //    new SelectListItem() { Value = "BZ", Text = "BZ" },
        //    new SelectListItem() { Value = "BJ", Text = "BJ" },
        //    new SelectListItem() { Value = "BM", Text = "BM" },
        //    new SelectListItem() { Value = "BT", Text = "BT" },
        //    new SelectListItem() { Value = "BO", Text = "BO" },
        //    new SelectListItem() { Value = "BQ", Text = "BQ" },
        //    new SelectListItem() { Value = "BA", Text = "BA" },
        //    new SelectListItem() { Value = "BW", Text = "BW" },
        //    new SelectListItem() { Value = "BV", Text = "BV" },
        //    new SelectListItem() { Value = "BR", Text = "BR" },
        //    new SelectListItem() { Value = "IO", Text = "IO" },
        //    new SelectListItem() { Value = "BN", Text = "BN" },
        //    new SelectListItem() { Value = "BG", Text = "BG" },
        //    new SelectListItem() { Value = "BF", Text = "BF" },
        //    new SelectListItem() { Value = "BI", Text = "BI" },
        //    new SelectListItem() { Value = "CV", Text = "CV" },
        //    new SelectListItem() { Value = "KH", Text = "KH" },
        //    new SelectListItem() { Value = "CM", Text = "CM" },
        //    new SelectListItem() { Value = "CA", Text = "CA" },
        //    new SelectListItem() { Value = "KY", Text = "KY" },
        //    new SelectListItem() { Value = "CF", Text = "CF" },
        //    new SelectListItem() { Value = "TD", Text = "TD" },
        //    new SelectListItem() { Value = "CL", Text = "CL" },
        //    new SelectListItem() { Value = "CN", Text = "CN" },
        //    new SelectListItem() { Value = "CX", Text = "CX" },
        //    new SelectListItem() { Value = "CC", Text = "CC" },
        //    new SelectListItem() { Value = "CO", Text = "CO" },
        //    new SelectListItem() { Value = "KM", Text = "KM" },
        //    new SelectListItem() { Value = "CD", Text = "CD" },
        //    new SelectListItem() { Value = "CG", Text = "CG" },
        //    new SelectListItem() { Value = "CK", Text = "CK" },
        //    new SelectListItem() { Value = "CR", Text = "CR" },
        //    new SelectListItem() { Value = "HR", Text = "HR" },
        //    new SelectListItem() { Value = "CU", Text = "CU" },
        //    new SelectListItem() { Value = "CW", Text = "CW" },
        //    new SelectListItem() { Value = "CY", Text = "CY" },
        //    new SelectListItem() { Value = "CZ", Text = "CZ" },
        //    new SelectListItem() { Value = "CI", Text = "CI" },
        //    new SelectListItem() { Value = "DK", Text = "DK" },
        //    new SelectListItem() { Value = "DJ", Text = "DJ" },
        //    new SelectListItem() { Value = "DM", Text = "DM" },
        //    new SelectListItem() { Value = "DO", Text = "DO" },
        //    new SelectListItem() { Value = "EC", Text = "EC" },
        //    new SelectListItem() { Value = "EG", Text = "EG" },
        //    new SelectListItem() { Value = "SV", Text = "SV" },
        //    new SelectListItem() { Value = "GQ", Text = "GQ" },
        //    new SelectListItem() { Value = "ER", Text = "ER" },
        //    new SelectListItem() { Value = "EE", Text = "EE" },
        //    new SelectListItem() { Value = "SZ", Text = "SZ" },
        //    new SelectListItem() { Value = "ET", Text = "ET" },
        //    new SelectListItem() { Value = "FK", Text = "FK" },
        //    new SelectListItem() { Value = "FO", Text = "FO" },
        //    new SelectListItem() { Value = "FJ", Text = "FJ" },
        //    new SelectListItem() { Value = "FI", Text = "FI" },
        //    new SelectListItem() { Value = "FR", Text = "FR" },
        //    new SelectListItem() { Value = "GF", Text = "GF" },
        //    new SelectListItem() { Value = "PF", Text = "PF" },
        //    new SelectListItem() { Value = "TF", Text = "TF" },
        //    new SelectListItem() { Value = "GA", Text = "GA" },
        //    new SelectListItem() { Value = "GM", Text = "GM" },
        //    new SelectListItem() { Value = "GE", Text = "GE" },
        //    new SelectListItem() { Value = "DE", Text = "DE" },
        //    new SelectListItem() { Value = "GH", Text = "GH" },
        //    new SelectListItem() { Value = "GI", Text = "GI" },
        //    new SelectListItem() { Value = "GR", Text = "GR" },
        //    new SelectListItem() { Value = "GL", Text = "GL" },
        //    new SelectListItem() { Value = "GD", Text = "GD" },
        //    new SelectListItem() { Value = "GP", Text = "GP" },
        //    new SelectListItem() { Value = "GU", Text = "GU" },
        //    new SelectListItem() { Value = "GT", Text = "GT" },
        //    new SelectListItem() { Value = "GG", Text = "GG" },
        //    new SelectListItem() { Value = "GN", Text = "GN" },
        //    new SelectListItem() { Value = "GW", Text = "GW" },
        //    new SelectListItem() { Value = "GY", Text = "GY" },
        //    new SelectListItem() { Value = "HT", Text = "HT" },
        //    new SelectListItem() { Value = "HM", Text = "HM" },
        //    new SelectListItem() { Value = "VA", Text = "VA" },
        //    new SelectListItem() { Value = "HN", Text = "HN" },
        //    new SelectListItem() { Value = "HK", Text = "HK" },
        //    new SelectListItem() { Value = "HU", Text = "HU" },
        //    new SelectListItem() { Value = "IS", Text = "IS" },
        //    new SelectListItem() { Value = "IN", Text = "IN" },
        //    new SelectListItem() { Value = "ID", Text = "ID" },
        //    new SelectListItem() { Value = "IR", Text = "IR" },
        //    new SelectListItem() { Value = "IQ", Text = "IQ" },
        //    new SelectListItem() { Value = "IE", Text = "IE" },
        //    new SelectListItem() { Value = "IM", Text = "IM" },
        //    new SelectListItem() { Value = "IL", Text = "IL" },
        //    new SelectListItem() { Value = "IT", Text = "IT" },
        //    new SelectListItem() { Value = "JM", Text = "JM" },
        //    new SelectListItem() { Value = "JP", Text = "JP" },
        //    new SelectListItem() { Value = "JE", Text = "JE" },
        //    new SelectListItem() { Value = "JO", Text = "JO" },
        //    new SelectListItem() { Value = "KZ", Text = "KZ" },
        //    new SelectListItem() { Value = "KE", Text = "KE" },
        //    new SelectListItem() { Value = "KI", Text = "KI" },
        //    new SelectListItem() { Value = "KP", Text = "KP" },
        //    new SelectListItem() { Value = "KR", Text = "KR" },
        //    new SelectListItem() { Value = "KW", Text = "KW" },
        //    new SelectListItem() { Value = "KG", Text = "KG" },
        //    new SelectListItem() { Value = "LA", Text = "LA" },
        //    new SelectListItem() { Value = "LV", Text = "LV" },
        //    new SelectListItem() { Value = "LB", Text = "LB" },
        //    new SelectListItem() { Value = "LS", Text = "LS" },
        //    new SelectListItem() { Value = "LR", Text = "LR" },
        //    new SelectListItem() { Value = "LY", Text = "LY" },
        //    new SelectListItem() { Value = "LI", Text = "LI" },
        //    new SelectListItem() { Value = "LT", Text = "LT" },
        //    new SelectListItem() { Value = "LU", Text = "LU" },
        //    new SelectListItem() { Value = "MO", Text = "MO" },
        //    new SelectListItem() { Value = "MG", Text = "MG" },
        //    new SelectListItem() { Value = "MW", Text = "MW" },
        //    new SelectListItem() { Value = "MY", Text = "MY" },
        //    new SelectListItem() { Value = "MV", Text = "MV" },
        //    new SelectListItem() { Value = "ML", Text = "ML" },
        //    new SelectListItem() { Value = "MT", Text = "MT" },
        //    new SelectListItem() { Value = "MH", Text = "MH" },
        //    new SelectListItem() { Value = "MQ", Text = "MQ" },
        //    new SelectListItem() { Value = "MR", Text = "MR" },
        //    new SelectListItem() { Value = "MU", Text = "MU" },
        //    new SelectListItem() { Value = "YT", Text = "YT" },
        //    new SelectListItem() { Value = "MX", Text = "MX" },
        //    new SelectListItem() { Value = "FM", Text = "FM" },
        //    new SelectListItem() { Value = "MD", Text = "MD" },
        //    new SelectListItem() { Value = "MC", Text = "MC" },
        //    new SelectListItem() { Value = "MN", Text = "MN" },
        //    new SelectListItem() { Value = "ME", Text = "ME" },
        //    new SelectListItem() { Value = "MS", Text = "MS" },
        //    new SelectListItem() { Value = "MA", Text = "MA" },
        //    new SelectListItem() { Value = "MZ", Text = "MZ" },
        //    new SelectListItem() { Value = "MM", Text = "MM" },
        //    new SelectListItem() { Value = "NA", Text = "NA" },
        //    new SelectListItem() { Value = "NR", Text = "NR" },
        //    new SelectListItem() { Value = "NP", Text = "NP" },
        //    new SelectListItem() { Value = "NL", Text = "NL" },
        //    new SelectListItem() { Value = "NC", Text = "NC" },
        //    new SelectListItem() { Value = "NZ", Text = "NZ" },
        //    new SelectListItem() { Value = "NI", Text = "NI" },
        //    new SelectListItem() { Value = "NE", Text = "NE" },
        //    new SelectListItem() { Value = "NG", Text = "NG" },
        //    new SelectListItem() { Value = "NU", Text = "NU" },
        //    new SelectListItem() { Value = "NF", Text = "NF" },
        //    new SelectListItem() { Value = "MP", Text = "MP" },
        //    new SelectListItem() { Value = "NO", Text = "NO" },
        //    new SelectListItem() { Value = "OM", Text = "OM" },
        //    new SelectListItem() { Value = "PK", Text = "PK" },
        //    new SelectListItem() { Value = "PW", Text = "PW" },
        //    new SelectListItem() { Value = "PS", Text = "PS" },
        //    new SelectListItem() { Value = "PA", Text = "PA" },
        //    new SelectListItem() { Value = "PG", Text = "PG" },
        //    new SelectListItem() { Value = "PY", Text = "PY" },
        //    new SelectListItem() { Value = "PE", Text = "PE" },
        //    new SelectListItem() { Value = "PH", Text = "PH" },
        //    new SelectListItem() { Value = "PN", Text = "PN" },
        //    new SelectListItem() { Value = "PL", Text = "PL" },
        //    new SelectListItem() { Value = "PT", Text = "PT" },
        //    new SelectListItem() { Value = "PR", Text = "PR" },
        //    new SelectListItem() { Value = "QA", Text = "QA" },
        //    new SelectListItem() { Value = "MK", Text = "MK" },
        //    new SelectListItem() { Value = "RO", Text = "RO" },
        //    new SelectListItem() { Value = "RU", Text = "RU" },
        //    new SelectListItem() { Value = "RW", Text = "RW" },
        //    new SelectListItem() { Value = "RE", Text = "RE" },
        //    new SelectListItem() { Value = "BL", Text = "BL" },
        //    new SelectListItem() { Value = "SH", Text = "SH" },
        //    new SelectListItem() { Value = "KN", Text = "KN" },
        //    new SelectListItem() { Value = "LC", Text = "LC" },
        //    new SelectListItem() { Value = "MF", Text = "MF" },
        //    new SelectListItem() { Value = "PM", Text = "PM" },
        //    new SelectListItem() { Value = "VC", Text = "VC" },
        //    new SelectListItem() { Value = "WS", Text = "WS" },
        //    new SelectListItem() { Value = "SM", Text = "SM" },
        //    new SelectListItem() { Value = "ST", Text = "ST" },
        //    new SelectListItem() { Value = "SA", Text = "SA" },
        //    new SelectListItem() { Value = "SN", Text = "SN" },
        //    new SelectListItem() { Value = "RS", Text = "RS" },
        //    new SelectListItem() { Value = "SC", Text = "SC" },
        //    new SelectListItem() { Value = "SL", Text = "SL" },
        //    new SelectListItem() { Value = "SG", Text = "SG" },
        //    new SelectListItem() { Value = "SX", Text = "SX" },
        //    new SelectListItem() { Value = "SK", Text = "SK" },
        //    new SelectListItem() { Value = "SI", Text = "SI" },
        //    new SelectListItem() { Value = "SB", Text = "SB" },
        //    new SelectListItem() { Value = "SO", Text = "SO" },
        //    new SelectListItem() { Value = "ZA", Text = "ZA" },
        //    new SelectListItem() { Value = "GS", Text = "GS" },
        //    new SelectListItem() { Value = "SS", Text = "SS" },
        //    new SelectListItem() { Value = "ES", Text = "ES" },
        //    new SelectListItem() { Value = "LK", Text = "LK" },
        //    new SelectListItem() { Value = "SD", Text = "SD" },
        //    new SelectListItem() { Value = "SR", Text = "SR" },
        //    new SelectListItem() { Value = "SJ", Text = "SJ" },
        //    new SelectListItem() { Value = "SE", Text = "SE" },
        //    new SelectListItem() { Value = "CH", Text = "CH" },
        //    new SelectListItem() { Value = "SY", Text = "SY" },
        //    new SelectListItem() { Value = "TW", Text = "TW" },
        //    new SelectListItem() { Value = "TJ", Text = "TJ" },
        //    new SelectListItem() { Value = "TZ", Text = "TZ" },
        //    new SelectListItem() { Value = "TH", Text = "TH" },
        //    new SelectListItem() { Value = "TL", Text = "TL" },
        //    new SelectListItem() { Value = "TG", Text = "TG" },
        //    new SelectListItem() { Value = "TK", Text = "TK" },
        //    new SelectListItem() { Value = "TO", Text = "TO" },
        //    new SelectListItem() { Value = "TT", Text = "TT" },
        //    new SelectListItem() { Value = "TN", Text = "TN" },
        //    new SelectListItem() { Value = "TR", Text = "TR" },
        //    new SelectListItem() { Value = "TM", Text = "TM" },
        //    new SelectListItem() { Value = "TC", Text = "TC" },
        //    new SelectListItem() { Value = "TV", Text = "TV" },
        //    new SelectListItem() { Value = "UG", Text = "UG" },
        //    new SelectListItem() { Value = "UA", Text = "UA" },
        //    new SelectListItem() { Value = "AE", Text = "AE" },
        //    new SelectListItem() { Value = "GB", Text = "GB" },
        //    new SelectListItem() { Value = "UM", Text = "UM" },
        //    new SelectListItem() { Value = "US", Text = "US" },
        //    new SelectListItem() { Value = "UY", Text = "UY" },
        //    new SelectListItem() { Value = "UZ", Text = "UZ" },
        //    new SelectListItem() { Value = "VU", Text = "VU" },
        //    new SelectListItem() { Value = "VE", Text = "VE" },
        //    new SelectListItem() { Value = "VN", Text = "VN" },
        //    new SelectListItem() { Value = "VG", Text = "VG" },
        //    new SelectListItem() { Value = "VI", Text = "VI" },
        //    new SelectListItem() { Value = "WF", Text = "WF" },
        //    new SelectListItem() { Value = "EH", Text = "EH" },
        //    new SelectListItem() { Value = "YE", Text = "YE" },
        //    new SelectListItem() { Value = "ZM", Text = "ZM" },
        //    new SelectListItem() { Value = "ZW", Text = "ZW" },
        //    new SelectListItem() { Value = "AX", Text = "AX" },
        //};

        //public static readonly List<SelectListItem> Nationalities = new List<SelectListItem>
        //{
        //    new SelectListItem() { Value = "Afghanistan", Text = "Afghanistan" },
        //    new SelectListItem() { Value = "Albania", Text = "Albania" },
        //    new SelectListItem() { Value = "Algeria", Text = "Algeria" },
        //    new SelectListItem() { Value = "American Samoa", Text = "American Samoa" },
        //    new SelectListItem() { Value = "Andorra", Text = "Andorra" },
        //    new SelectListItem() { Value = "Angola", Text = "Angola" },
        //    new SelectListItem() { Value = "Anguilla", Text = "Anguilla" },
        //    new SelectListItem() { Value = "Antarctica", Text = "Antarctica" },
        //    new SelectListItem() { Value = "Antigua and Barbuda", Text = "Antigua and Barbuda" },
        //    new SelectListItem() { Value = "Argentina", Text = "Argentina" },
        //    new SelectListItem() { Value = "Armenia", Text = "Armenia" },
        //    new SelectListItem() { Value = "Aruba", Text = "Aruba" },
        //    new SelectListItem() { Value = "Australia", Text = "Australia" },
        //    new SelectListItem() { Value = "Austria", Text = "Austria" },
        //    new SelectListItem() { Value = "Azerbaijan", Text = "Azerbaijan" },
        //    new SelectListItem() { Value = "Bahamas", Text = "Bahamas" },
        //    new SelectListItem() { Value = "Bahrain", Text = "Bahrain" },
        //    new SelectListItem() { Value = "Bangladesh", Text = "Bangladesh" },
        //    new SelectListItem() { Value = "Barbados", Text = "Barbados" },
        //    new SelectListItem() { Value = "Belarus", Text = "Belarus" },
        //    new SelectListItem() { Value = "Belgium", Text = "Belgium" },
        //    new SelectListItem() { Value = "Belize", Text = "Belize" },
        //    new SelectListItem() { Value = "Benin", Text = "Benin" },
        //    new SelectListItem() { Value = "Bermuda", Text = "Bermuda" },
        //    new SelectListItem() { Value = "Bhutan", Text = "Bhutan" },
        //    new SelectListItem() { Value = "Bolivia (Plurinational State of)", Text = "Bolivia (Plurinational State of)" },
        //    new SelectListItem() { Value = "Bonaire, Sint Eustatius and Saba", Text = "Bonaire, Sint Eustatius and Saba" },
        //    new SelectListItem() { Value = "Bosnia and Herzegovina", Text = "Bosnia and Herzegovina" },
        //    new SelectListItem() { Value = "Botswana", Text = "Botswana" },
        //    new SelectListItem() { Value = "Bouvet Island", Text = "Bouvet Island" },
        //    new SelectListItem() { Value = "Brazil", Text = "Brazil" },
        //    new SelectListItem() { Value = "British Indian Ocean Territory", Text = "British Indian Ocean Territory" },
        //    new SelectListItem() { Value = "Brunei Darussalam", Text = "Brunei Darussalam" },
        //    new SelectListItem() { Value = "Bulgaria", Text = "Bulgaria" },
        //    new SelectListItem() { Value = "Burkina Faso", Text = "Burkina Faso" },
        //    new SelectListItem() { Value = "Burundi", Text = "Burundi" },
        //    new SelectListItem() { Value = "Cabo Verde", Text = "Cabo Verde" },
        //    new SelectListItem() { Value = "Cambodia", Text = "Cambodia" },
        //    new SelectListItem() { Value = "Cameroon", Text = "Cameroon" },
        //    new SelectListItem() { Value = "Canada", Text = "Canada" },
        //    new SelectListItem() { Value = "Cayman Islands", Text = "Cayman Islands" },
        //    new SelectListItem() { Value = "Central African Republic", Text = "Central African Republic" },
        //    new SelectListItem() { Value = "Chad", Text = "Chad" },
        //    new SelectListItem() { Value = "Chile", Text = "Chile" },
        //    new SelectListItem() { Value = "China", Text = "China" },
        //    new SelectListItem() { Value = "Christmas Island", Text = "Christmas Island" },
        //    new SelectListItem() { Value = "Cocos (Keeling) Islands", Text = "Cocos (Keeling) Islands" },
        //    new SelectListItem() { Value = "Colombia", Text = "Colombia" },
        //    new SelectListItem() { Value = "Comoros", Text = "Comoros" },
        //    new SelectListItem() { Value = "Democratic Republic Congo", Text = "Democratic Republic Congo" },
        //    new SelectListItem() { Value = "Congo", Text = "Congo" },
        //    new SelectListItem() { Value = "Cook Islands", Text = "Cook Islands" },
        //    new SelectListItem() { Value = "Costa Rica", Text = "Costa Rica" },
        //    new SelectListItem() { Value = "Croatia", Text = "Croatia" },
        //    new SelectListItem() { Value = "Cuba", Text = "Cuba" },
        //    new SelectListItem() { Value = "Curaçao", Text = "Curaçao" },
        //    new SelectListItem() { Value = "Cyprus", Text = "Cyprus" },
        //    new SelectListItem() { Value = "Czechia", Text = "Czechia" },
        //    new SelectListItem() { Value = "Côte d'Ivoire", Text = "Côte d'Ivoire" },
        //    new SelectListItem() { Value = "Denmark", Text = "Denmark" },
        //    new SelectListItem() { Value = "Djibouti", Text = "Djibouti" },
        //    new SelectListItem() { Value = "Dominica", Text = "Dominica" },
        //    new SelectListItem() { Value = "Dominican Republic", Text = "Dominican Republic" },
        //    new SelectListItem() { Value = "Ecuador", Text = "Ecuador" },
        //    new SelectListItem() { Value = "Egypt", Text = "Egypt" },
        //    new SelectListItem() { Value = "El Salvador", Text = "El Salvador" },
        //    new SelectListItem() { Value = "Equatorial Guinea", Text = "Equatorial Guinea" },
        //    new SelectListItem() { Value = "Eritrea", Text = "Eritrea" },
        //    new SelectListItem() { Value = "Estonia", Text = "Estonia" },
        //    new SelectListItem() { Value = "Eswatini", Text = "Eswatini" },
        //    new SelectListItem() { Value = "Ethiopia", Text = "Ethiopia" },
        //    new SelectListItem() { Value = "Faroe Islands", Text = "Faroe Islands" },
        //    new SelectListItem() { Value = "Faroe", Text = "Faroe" },
        //    new SelectListItem() { Value = "Fiji", Text = "Fiji" },
        //    new SelectListItem() { Value = "Finland", Text = "Finland" },
        //    new SelectListItem() { Value = "France", Text = "France" },
        //    new SelectListItem() { Value = "French Polynesia", Text = "French Polynesia" },
        //    new SelectListItem() { Value = "French", Text = "French" },
        //    new SelectListItem() { Value = "French Southern Territories", Text = "French Southern Territories" },
        //    new SelectListItem() { Value = "Gabon", Text = "Gabon" },
        //    new SelectListItem() { Value = "Gambia", Text = "Gambia" },
        //    new SelectListItem() { Value = "Georgia", Text = "Georgia" },
        //    new SelectListItem() { Value = "Germany", Text = "Germany" },
        //    new SelectListItem() { Value = "Ghana", Text = "Ghana" },
        //    new SelectListItem() { Value = "Gibraltar", Text = "Gibraltar" },
        //    new SelectListItem() { Value = "Greece", Text = "Greece" },
        //    new SelectListItem() { Value = "Greenland", Text = "Greenland" },
        //    new SelectListItem() { Value = "Grenada", Text = "Grenada" },
        //    new SelectListItem() { Value = "Guadeloupe", Text = "Guadeloupe" },
        //    new SelectListItem() { Value = "Guam", Text = "Guam" },
        //    new SelectListItem() { Value = "Guatemala", Text = "Guatemala" },
        //    new SelectListItem() { Value = "Guernsey", Text = "Guernsey" },
        //    new SelectListItem() { Value = "Guinea", Text = "Guinea" },
        //    new SelectListItem() { Value = "Guinea-Bissau", Text = "Guinea-Bissau" },
        //    new SelectListItem() { Value = "Guyana", Text = "Guyana" },
        //    new SelectListItem() { Value = "Haiti", Text = "Haiti" },
        //    new SelectListItem() { Value = "Heard Island and McDonald Islands", Text = "Heard Island and McDonald Islands" },
        //    new SelectListItem() { Value = "Holy See", Text = "Holy See" },
        //    new SelectListItem() { Value = "Honduras", Text = "Honduras" },
        //    new SelectListItem() { Value = "Hong Kong", Text = "Hong Kong" },
        //    new SelectListItem() { Value = "Hungary", Text = "Hungary" },
        //    new SelectListItem() { Value = "Iceland", Text = "Iceland" },
        //    new SelectListItem() { Value = "India", Text = "India" },
        //    new SelectListItem() { Value = "Indonesia", Text = "Indonesia" },
        //    new SelectListItem() { Value = "Iran", Text = "Iran" },
        //    new SelectListItem() { Value = "Iraq", Text = "Iraq" },
        //    new SelectListItem() { Value = "Ireland", Text = "Ireland" },
        //    new SelectListItem() { Value = "Isle of Man", Text = "Isle of Man" },
        //    new SelectListItem() { Value = "Israel", Text = "Israel" },
        //    new SelectListItem() { Value = "Italy", Text = "Italy" },
        //    new SelectListItem() { Value = "Jamaica", Text = "Jamaica" },
        //    new SelectListItem() { Value = "Japan", Text = "Japan" },
        //    new SelectListItem() { Value = "Jersey", Text = "Jersey" },
        //    new SelectListItem() { Value = "Jordan", Text = "Jordan" },
        //    new SelectListItem() { Value = "Kazakhstan", Text = "Kazakhstan" },
        //    new SelectListItem() { Value = "Kenya", Text = "Kenya" },
        //    new SelectListItem() { Value = "Kiribati", Text = "Kiribati" },
        //    new SelectListItem() { Value = "Korea Democratic People's Republic", Text = "Korea Democratic People's Republic" },
        //    new SelectListItem() { Value = "Korea Republic", Text = "Korea Republic" },
        //    new SelectListItem() { Value = "Kuwait", Text = "Kuwait" },
        //    new SelectListItem() { Value = "Kyrgyzstan", Text = "Kyrgyzstan" },
        //    new SelectListItem() { Value = "Lao People's Democratic Republic", Text = "Lao People's Democratic Republic" },
        //    new SelectListItem() { Value = "Latvia", Text = "Latvia" },
        //    new SelectListItem() { Value = "Lebanon", Text = "Lebanon" },
        //    new SelectListItem() { Value = "Lesotho", Text = "Lesotho" },
        //    new SelectListItem() { Value = "Liberia", Text = "Liberia" },
        //    new SelectListItem() { Value = "Libya", Text = "Libya" },
        //    new SelectListItem() { Value = "Liechtenstein", Text = "Liechtenstein" },
        //    new SelectListItem() { Value = "Lithuania", Text = "Lithuania" },
        //    new SelectListItem() { Value = "Luxembourg", Text = "Luxembourg" },
        //    new SelectListItem() { Value = "Macao", Text = "Macao" },
        //    new SelectListItem() { Value = "Madagascar", Text = "Madagascar" },
        //    new SelectListItem() { Value = "Malawi", Text = "Malawi" },
        //    new SelectListItem() { Value = "Malaysia", Text = "Malaysia" },
        //    new SelectListItem() { Value = "Maldives", Text = "Maldives" },
        //    new SelectListItem() { Value = "Mali", Text = "Mali" },
        //    new SelectListItem() { Value = "Malta", Text = "Malta" },
        //    new SelectListItem() { Value = "Marshall Islands", Text = "Marshall Islands" },
        //    new SelectListItem() { Value = "Martinique", Text = "Martinique" },
        //    new SelectListItem() { Value = "Mauritania", Text = "Mauritania" },
        //    new SelectListItem() { Value = "Mauritius", Text = "Mauritius" },
        //    new SelectListItem() { Value = "Mayotte", Text = "Mayotte" },
        //    new SelectListItem() { Value = "Mexico", Text = "Mexico" },
        //    new SelectListItem() { Value = "Micronesia Federated States", Text = "Micronesia Federated States" },
        //    new SelectListItem() { Value = "Moldova Republic", Text = "Moldova Republic" },
        //    new SelectListItem() { Value = "Monaco", Text = "Monaco" },
        //    new SelectListItem() { Value = "Mongolia", Text = "Mongolia" },
        //    new SelectListItem() { Value = "Montenegro", Text = "Montenegro" },
        //    new SelectListItem() { Value = "Montserrat", Text = "Montserrat" },
        //    new SelectListItem() { Value = "Morocco", Text = "Morocco" },
        //    new SelectListItem() { Value = "Mozambique", Text = "Mozambique" },
        //    new SelectListItem() { Value = "Myanmar", Text = "Myanmar" },
        //    new SelectListItem() { Value = "Namibia", Text = "Namibia" },
        //    new SelectListItem() { Value = "Nauru", Text = "Nauru" },
        //    new SelectListItem() { Value = "Nepal", Text = "Nepal" },
        //    new SelectListItem() { Value = "Netherlands", Text = "Netherlands" },
        //    new SelectListItem() { Value = "New Caledonia", Text = "New Caledonia" },
        //    new SelectListItem() { Value = "New Zealand", Text = "New Zealand" },
        //    new SelectListItem() { Value = "Nicaragua", Text = "Nicaragua" },
        //    new SelectListItem() { Value = "Niger", Text = "Niger" },
        //    new SelectListItem() { Value = "Nigeria", Text = "Nigeria" },
        //    new SelectListItem() { Value = "Niue", Text = "Niue" },
        //    new SelectListItem() { Value = "Norfolk Island", Text = "Norfolk Island" },
        //    new SelectListItem() { Value = "Northern Mariana Islands", Text = "Northern Mariana Islands" },
        //    new SelectListItem() { Value = "Norway", Text = "Norway" },
        //    new SelectListItem() { Value = "Oman", Text = "Oman" },
        //    new SelectListItem() { Value = "Pakistan", Text = "Pakistan" },
        //    new SelectListItem() { Value = "Palau", Text = "Palau" },
        //    new SelectListItem() { Value = "Palestine,", Text = "Palestine," },
        //    new SelectListItem() { Value = "Panama", Text = "Panama" },
        //    new SelectListItem() { Value = "Papua New Guinea", Text = "Papua New Guinea" },
        //    new SelectListItem() { Value = "Paraguay", Text = "Paraguay" },
        //    new SelectListItem() { Value = "Peru", Text = "Peru" },
        //    new SelectListItem() { Value = "Philippines", Text = "Philippines" },
        //    new SelectListItem() { Value = "Pitcairn", Text = "Pitcairn" },
        //    new SelectListItem() { Value = "Poland", Text = "Poland" },
        //    new SelectListItem() { Value = "Portugal", Text = "Portugal" },
        //    new SelectListItem() { Value = "Puerto Rico", Text = "Puerto Rico" },
        //    new SelectListItem() { Value = "Qatar", Text = "Qatar" },
        //    new SelectListItem() { Value = "Republic of North Macedonia", Text = "Republic of North Macedonia" },
        //    new SelectListItem() { Value = "Romania", Text = "Romania" },
        //    new SelectListItem() { Value = "Russian Federation", Text = "Russian Federation" },
        //    new SelectListItem() { Value = "Rwanda", Text = "Rwanda" },
        //    new SelectListItem() { Value = "Réunion", Text = "Réunion" },
        //    new SelectListItem() { Value = "Saint Barthélemy", Text = "Saint Barthélemy" },
        //    new SelectListItem() { Value = "Saint Helena, Ascension and Tristan da Cunha", Text = "Saint Helena, Ascension and Tristan da Cunha" },
        //    new SelectListItem() { Value = "Saint Kitts and Nevis", Text = "Saint Kitts and Nevis" },
        //    new SelectListItem() { Value = "Saint Lucia", Text = "Saint Lucia" },
        //    new SelectListItem() { Value = "Saint Martin (French part)", Text = "Saint Martin (French part)" },
        //    new SelectListItem() { Value = "Saint Pierre and Miquelon", Text = "Saint Pierre and Miquelon" },
        //    new SelectListItem() { Value = "Saint Vincent and the Grenadines", Text = "Saint Vincent and the Grenadines" },
        //    new SelectListItem() { Value = "Samoa", Text = "Samoa" },
        //    new SelectListItem() { Value = "San Marino", Text = "San Marino" },
        //    new SelectListItem() { Value = "Sao Tome and Principe", Text = "Sao Tome and Principe" },
        //    new SelectListItem() { Value = "Saudi Arabia", Text = "Saudi Arabia" },
        //    new SelectListItem() { Value = "Senegal", Text = "Senegal" },
        //    new SelectListItem() { Value = "Serbia", Text = "Serbia" },
        //    new SelectListItem() { Value = "Seychelles", Text = "Seychelles" },
        //    new SelectListItem() { Value = "Sierra Leone", Text = "Sierra Leone" },
        //    new SelectListItem() { Value = "Singapore", Text = "Singapore" },
        //    new SelectListItem() { Value = "Sint Maarten (Dutch part)", Text = "Sint Maarten (Dutch part)" },
        //    new SelectListItem() { Value = "Slovakia", Text = "Slovakia" },
        //    new SelectListItem() { Value = "Slovenia", Text = "Slovenia" },
        //    new SelectListItem() { Value = "Solomon Islands", Text = "Solomon Islands" },
        //    new SelectListItem() { Value = "Somalia", Text = "Somalia" },
        //    new SelectListItem() { Value = "South Africa", Text = "South Africa" },
        //    new SelectListItem() { Value = "South Georgia and the South Sandwich Islands", Text = "South Georgia and the South Sandwich Islands" },
        //    new SelectListItem() { Value = "South Sudan", Text = "South Sudan" },
        //    new SelectListItem() { Value = "Spain", Text = "Spain" },
        //    new SelectListItem() { Value = "Sri Lanka", Text = "Sri Lanka" },
        //    new SelectListItem() { Value = "Sudan", Text = "Sudan" },
        //    new SelectListItem() { Value = "Suriname", Text = "Suriname" },
        //    new SelectListItem() { Value = "Svalbard and Jan Mayen", Text = "Svalbard and Jan Mayen" },
        //    new SelectListItem() { Value = "Sweden", Text = "Sweden" },
        //    new SelectListItem() { Value = "Switzerland", Text = "Switzerland" },
        //    new SelectListItem() { Value = "Syrian Arab Republic", Text = "Syrian Arab Republic" },
        //    new SelectListItem() { Value = "Taiwan (Province of China)", Text = "Taiwan (Province of China)" },
        //    new SelectListItem() { Value = "Tajikistan", Text = "Tajikistan" },
        //    new SelectListItem() { Value = "Tanzania, United Republic", Text = "Tanzania, United Republic" },
        //    new SelectListItem() { Value = "Thailand", Text = "Thailand" },
        //    new SelectListItem() { Value = "Timor-Leste", Text = "Timor-Leste" },
        //    new SelectListItem() { Value = "Togo", Text = "Togo" },
        //    new SelectListItem() { Value = "Tokelau", Text = "Tokelau" },
        //    new SelectListItem() { Value = "Tonga", Text = "Tonga" },
        //    new SelectListItem() { Value = "Trinidad and Tobago", Text = "Trinidad and Tobago" },
        //    new SelectListItem() { Value = "Tunisia", Text = "Tunisia" },
        //    new SelectListItem() { Value = "Turkey", Text = "Turkey" },
        //    new SelectListItem() { Value = "Turkmenistan", Text = "Turkmenistan" },
        //    new SelectListItem() { Value = "Turks and Caicos Islands", Text = "Turks and Caicos Islands" },
        //    new SelectListItem() { Value = "Tuvalu", Text = "Tuvalu" },
        //    new SelectListItem() { Value = "Uganda", Text = "Uganda" },
        //    new SelectListItem() { Value = "Ukraine", Text = "Ukraine" },
        //    new SelectListItem() { Value = "United Arab Emirates", Text = "United Arab Emirates" },
        //    new SelectListItem() { Value = "United Kingdom of Great Britain and Northern Ireland", Text = "United Kingdom of Great Britain and Northern Ireland" },
        //    new SelectListItem() { Value = "United States Minor Outlying Islands", Text = "United States Minor Outlying Islands" },
        //    new SelectListItem() { Value = "United States of America", Text = "United States of America" },
        //    new SelectListItem() { Value = "Uruguay", Text = "Uruguay" },
        //    new SelectListItem() { Value = "Uzbekistan", Text = "Uzbekistan" },
        //    new SelectListItem() { Value = "Vanuatu", Text = "Vanuatu" },
        //    new SelectListItem() { Value = "Venezuela", Text = "Venezuela" },
        //    new SelectListItem() { Value = "Viet Nam", Text = "Viet Nam" },
        //    new SelectListItem() { Value = "Virgin Islands (British)", Text = "Virgin Islands (British)" },
        //    new SelectListItem() { Value = "Virgin Islands (U.S.)", Text = "Virgin Islands (U.S.)" },
        //    new SelectListItem() { Value = "Wallis and Futuna", Text = "Wallis and Futuna" },
        //    new SelectListItem() { Value = "Western Sahara", Text = "Western Sahara" },
        //    new SelectListItem() { Value = "Yemen", Text = "Yemen" },
        //    new SelectListItem() { Value = "Zambia", Text = "Zambia" },
        //    new SelectListItem() { Value = "Zimbabwe", Text = "Zimbabwe" },
        //    new SelectListItem() { Value = "Åland Islands", Text = "Åland Islands" },
        //};

        //public static readonly List<SelectListItem> Nationality_Code = new List<SelectListItem>
        //{
        //    new SelectListItem() { Value = "Afghanistan", Text = "AF" },
        //    new SelectListItem() { Value = "Albania", Text = "AL" },
        //    new SelectListItem() { Value = "Algeria", Text = "DZ" },
        //    new SelectListItem() { Value = "American Samoa", Text = "AS" },
        //    new SelectListItem() { Value = "Andorra", Text = "AD" },
        //    new SelectListItem() { Value = "Angola", Text = "AO" },
        //    new SelectListItem() { Value = "Anguilla", Text = "AI" },
        //    new SelectListItem() { Value = "Antarctica", Text = "AQ" },
        //    new SelectListItem() { Value = "Antigua and Barbuda", Text = "AB" },
        //    new SelectListItem() { Value = "Argentina", Text = "AR" },
        //    new SelectListItem() { Value = "Armenia", Text = "AM" },
        //    new SelectListItem() { Value = "Aruba", Text = "AW" },
        //    new SelectListItem() { Value = "Australia", Text = "AU" },
        //    new SelectListItem() { Value = "Austria", Text = "AT" },
        //    new SelectListItem() { Value = "Azerbaijan", Text = "AZ" },
        //    new SelectListItem() { Value = "Bahamas", Text = "BS" },
        //    new SelectListItem() { Value = "Bahrain", Text = "BH" },
        //    new SelectListItem() { Value = "Bangladesh", Text = "BD" },
        //    new SelectListItem() { Value = "Barbados", Text = "BB" },
        //    new SelectListItem() { Value = "Belarus", Text = "BY" },
        //    new SelectListItem() { Value = "Belgium", Text = "BE" },
        //    new SelectListItem() { Value = "Belize", Text = "BZ" },
        //    new SelectListItem() { Value = "Benin", Text = "BJ" },
        //    new SelectListItem() { Value = "Bermuda", Text = "BM" },
        //    new SelectListItem() { Value = "Bhutan", Text = "BT" },
        //    new SelectListItem() { Value = "Bolivia (Plurinational State of)", Text = "BO" },
        //    new SelectListItem() { Value = "Bonaire, Sint Eustatius and Saba", Text = "BQ" },
        //    new SelectListItem() { Value = "Bosnia and Herzegovina", Text = "BA" },
        //    new SelectListItem() { Value = "Botswana", Text = "BW" },
        //    new SelectListItem() { Value = "Bouvet Island", Text = "BV" },
        //    new SelectListItem() { Value = "Brazil", Text = "BR" },
        //    new SelectListItem() { Value = "British Indian Ocean Territory", Text = "IO" },
        //    new SelectListItem() { Value = "Brunei Darussalam", Text = "BN" },
        //    new SelectListItem() { Value = "Bulgaria", Text = "BG" },
        //    new SelectListItem() { Value = "Burkina Faso", Text = "BF" },
        //    new SelectListItem() { Value = "Burundi", Text = "BI" },
        //    new SelectListItem() { Value = "Cabo Verde", Text = "CV" },
        //    new SelectListItem() { Value = "Cambodia", Text = "KH" },
        //    new SelectListItem() { Value = "Cameroon", Text = "CM" },
        //    new SelectListItem() { Value = "Canada", Text = "CA" },
        //    new SelectListItem() { Value = "Cayman Islands", Text = "KY" },
        //    new SelectListItem() { Value = "Central African Republic", Text = "CF" },
        //    new SelectListItem() { Value = "Chad", Text = "TD" },
        //    new SelectListItem() { Value = "Chile", Text = "CL" },
        //    new SelectListItem() { Value = "China", Text = "CN" },
        //    new SelectListItem() { Value = "Christmas Island", Text = "CX" },
        //    new SelectListItem() { Value = "Cocos (Keeling) Islands", Text = "CC" },
        //    new SelectListItem() { Value = "Colombia", Text = "CO" },
        //    new SelectListItem() { Value = "Comoros", Text = "KM" },
        //    new SelectListItem() { Value = "Democratic Republic Congo", Text = "CD" },
        //    new SelectListItem() { Value = "Congo", Text = "CG" },
        //    new SelectListItem() { Value = "Cook Islands", Text = "CK" },
        //    new SelectListItem() { Value = "Costa Rica", Text = "CR" },
        //    new SelectListItem() { Value = "Croatia", Text = "HR" },
        //    new SelectListItem() { Value = "Cuba", Text = "CU" },
        //    new SelectListItem() { Value = "Curaçao", Text = "CW" },
        //    new SelectListItem() { Value = "Cyprus", Text = "CY" },
        //    new SelectListItem() { Value = "Czechia", Text = "CZ" },
        //    new SelectListItem() { Value = "Côte d'Ivoire", Text = "CI" },
        //    new SelectListItem() { Value = "Denmark", Text = "DK" },
        //    new SelectListItem() { Value = "Djibouti", Text = "DJ" },
        //    new SelectListItem() { Value = "Dominica", Text = "DM" },
        //    new SelectListItem() { Value = "Dominican Republic", Text = "DO" },
        //    new SelectListItem() { Value = "Ecuador", Text = "EC" },
        //    new SelectListItem() { Value = "Egypt", Text = "EG" },
        //    new SelectListItem() { Value = "El Salvador", Text = "SV" },
        //    new SelectListItem() { Value = "Equatorial Guinea", Text = "GQ" },
        //    new SelectListItem() { Value = "Eritrea", Text = "ER" },
        //    new SelectListItem() { Value = "Estonia", Text = "EE" },
        //    new SelectListItem() { Value = "Eswatini", Text = "SZ" },
        //    new SelectListItem() { Value = "Ethiopia", Text = "ET" },
        //    new SelectListItem() { Value = "Faroe Islands", Text = "FK" },
        //    new SelectListItem() { Value = "Faroe", Text = "FO" },
        //    new SelectListItem() { Value = "Fiji", Text = "FJ" },
        //    new SelectListItem() { Value = "Finland", Text = "FI" },
        //    new SelectListItem() { Value = "France", Text = "FR" },
        //    new SelectListItem() { Value = "French Polynesia", Text = "GF" },
        //    new SelectListItem() { Value = "French", Text = "PF" },
        //    new SelectListItem() { Value = "French Southern Territories", Text = "TF" },
        //    new SelectListItem() { Value = "Gabon", Text = "GA" },
        //    new SelectListItem() { Value = "Gambia", Text = "GM" },
        //    new SelectListItem() { Value = "Georgia", Text = "GE" },
        //    new SelectListItem() { Value = "Germany", Text = "DE" },
        //    new SelectListItem() { Value = "Ghana", Text = "GH" },
        //    new SelectListItem() { Value = "Gibraltar", Text = "GI" },
        //    new SelectListItem() { Value = "Greece", Text = "GR" },
        //    new SelectListItem() { Value = "Greenland", Text = "GL" },
        //    new SelectListItem() { Value = "Grenada", Text = "GD" },
        //    new SelectListItem() { Value = "Guadeloupe", Text = "GP" },
        //    new SelectListItem() { Value = "Guam", Text = "GU" },
        //    new SelectListItem() { Value = "Guatemala", Text = "GT" },
        //    new SelectListItem() { Value = "Guernsey", Text = "GG" },
        //    new SelectListItem() { Value = "Guinea", Text = "GN" },
        //    new SelectListItem() { Value = "Guinea-Bissau", Text = "GW" },
        //    new SelectListItem() { Value = "Guyana", Text = "GY" },
        //    new SelectListItem() { Value = "Haiti", Text = "HT" },
        //    new SelectListItem() { Value = "Heard Island and McDonald Islands", Text = "HM" },
        //    new SelectListItem() { Value = "Holy See", Text = "VA" },
        //    new SelectListItem() { Value = "Honduras", Text = "HN" },
        //    new SelectListItem() { Value = "Hong Kong", Text = "HK" },
        //    new SelectListItem() { Value = "Hungary", Text = "HU" },
        //    new SelectListItem() { Value = "Iceland", Text = "IS" },
        //    new SelectListItem() { Value = "India", Text = "IN" },
        //    new SelectListItem() { Value = "Indonesia", Text = "ID" },
        //    new SelectListItem() { Value = "Iran", Text = "IR" },
        //    new SelectListItem() { Value = "Iraq", Text = "IQ" },
        //    new SelectListItem() { Value = "Ireland", Text = "IE" },
        //    new SelectListItem() { Value = "Isle of Man", Text = "IM" },
        //    new SelectListItem() { Value = "Israel", Text = "IL" },
        //    new SelectListItem() { Value = "Italy", Text = "IT" },
        //    new SelectListItem() { Value = "Jamaica", Text = "JM" },
        //    new SelectListItem() { Value = "Japan", Text = "JP" },
        //    new SelectListItem() { Value = "Jersey", Text = "JE" },
        //    new SelectListItem() { Value = "Jordan", Text = "JO" },
        //    new SelectListItem() { Value = "Kazakhstan", Text = "KZ" },
        //    new SelectListItem() { Value = "Kenya", Text = "KE" },
        //    new SelectListItem() { Value = "Kiribati", Text = "KI" },
        //    new SelectListItem() { Value = "Korea Democratic People's Republic", Text = "KP" },
        //    new SelectListItem() { Value = "Korea Republic", Text = "KR" },
        //    new SelectListItem() { Value = "Kuwait", Text = "KW" },
        //    new SelectListItem() { Value = "Kyrgyzstan", Text = "KG" },
        //    new SelectListItem() { Value = "Lao People's Democratic Republic", Text = "LA" },
        //    new SelectListItem() { Value = "Latvia", Text = "LV" },
        //    new SelectListItem() { Value = "Lebanon", Text = "LB" },
        //    new SelectListItem() { Value = "Lesotho", Text = "LS" },
        //    new SelectListItem() { Value = "Liberia", Text = "LR" },
        //    new SelectListItem() { Value = "Libya", Text = "LY" },
        //    new SelectListItem() { Value = "Liechtenstein", Text = "LI" },
        //    new SelectListItem() { Value = "Lithuania", Text = "LT" },
        //    new SelectListItem() { Value = "Luxembourg", Text = "LU" },
        //    new SelectListItem() { Value = "Macao", Text = "MO" },
        //    new SelectListItem() { Value = "Madagascar", Text = "MG" },
        //    new SelectListItem() { Value = "Malawi", Text = "MW" },
        //    new SelectListItem() { Value = "Malaysia", Text = "MY" },
        //    new SelectListItem() { Value = "Maldives", Text = "MV" },
        //    new SelectListItem() { Value = "Mali", Text = "ML" },
        //    new SelectListItem() { Value = "Malta", Text = "MT" },
        //    new SelectListItem() { Value = "Marshall Islands", Text = "MH" },
        //    new SelectListItem() { Value = "Martinique", Text = "MQ" },
        //    new SelectListItem() { Value = "Mauritania", Text = "MR" },
        //    new SelectListItem() { Value = "Mauritius", Text = "MU" },
        //    new SelectListItem() { Value = "Mayotte", Text = "YT" },
        //    new SelectListItem() { Value = "Mexico", Text = "MX" },
        //    new SelectListItem() { Value = "Micronesia Federated States", Text = "FM" },
        //    new SelectListItem() { Value = "Moldova Republic", Text = "MD" },
        //    new SelectListItem() { Value = "Monaco", Text = "MC" },
        //    new SelectListItem() { Value = "Mongolia", Text = "MN" },
        //    new SelectListItem() { Value = "Montenegro", Text = "ME" },
        //    new SelectListItem() { Value = "Montserrat", Text = "MS" },
        //    new SelectListItem() { Value = "Morocco", Text = "MA" },
        //    new SelectListItem() { Value = "Mozambique", Text = "MZ" },
        //    new SelectListItem() { Value = "Myanmar", Text = "MM" },
        //    new SelectListItem() { Value = "Namibia", Text = "NA" },
        //    new SelectListItem() { Value = "Nauru", Text = "NR" },
        //    new SelectListItem() { Value = "Nepal", Text = "NP" },
        //    new SelectListItem() { Value = "Netherlands", Text = "NL" },
        //    new SelectListItem() { Value = "New Caledonia", Text = "NC" },
        //    new SelectListItem() { Value = "New Zealand", Text = "NZ" },
        //    new SelectListItem() { Value = "Nicaragua", Text = "NI" },
        //    new SelectListItem() { Value = "Niger", Text = "NE" },
        //    new SelectListItem() { Value = "Nigeria", Text = "NG" },
        //    new SelectListItem() { Value = "Niue", Text = "NU" },
        //    new SelectListItem() { Value = "Norfolk Island", Text = "NF" },
        //    new SelectListItem() { Value = "Northern Mariana Islands", Text = "MP" },
        //    new SelectListItem() { Value = "Norway", Text = "NO" },
        //    new SelectListItem() { Value = "Oman", Text = "OM" },
        //    new SelectListItem() { Value = "Pakistan", Text = "PK" },
        //    new SelectListItem() { Value = "Palau", Text = "PW" },
        //    new SelectListItem() { Value = "Palestine,", Text = "PS" },
        //    new SelectListItem() { Value = "Panama", Text = "PA" },
        //    new SelectListItem() { Value = "Papua New Guinea", Text = "PG" },
        //    new SelectListItem() { Value = "Paraguay", Text = "PY" },
        //    new SelectListItem() { Value = "Peru", Text = "PE" },
        //    new SelectListItem() { Value = "Philippines", Text = "PH" },
        //    new SelectListItem() { Value = "Pitcairn", Text = "PN" },
        //    new SelectListItem() { Value = "Poland", Text = "PL" },
        //    new SelectListItem() { Value = "Portugal", Text = "PT" },
        //    new SelectListItem() { Value = "Puerto Rico", Text = "PR" },
        //    new SelectListItem() { Value = "Qatar", Text = "QA" },
        //    new SelectListItem() { Value = "Republic of North Macedonia", Text = "MK" },
        //    new SelectListItem() { Value = "Romania", Text = "RO" },
        //    new SelectListItem() { Value = "Russian Federation", Text = "RU" },
        //    new SelectListItem() { Value = "Rwanda", Text = "RW" },
        //    new SelectListItem() { Value = "Réunion", Text = "RE" },
        //    new SelectListItem() { Value = "Saint Barthélemy", Text = "BL" },
        //    new SelectListItem() { Value = "Saint Helena, Ascension and Tristan da Cunha", Text = "SH" },
        //    new SelectListItem() { Value = "Saint Kitts and Nevis", Text = "KN" },
        //    new SelectListItem() { Value = "Saint Lucia", Text = "LC" },
        //    new SelectListItem() { Value = "Saint Martin (French part)", Text = "MF" },
        //    new SelectListItem() { Value = "Saint Pierre and Miquelon", Text = "PM" },
        //    new SelectListItem() { Value = "Saint Vincent and the Grenadines", Text = "VC" },
        //    new SelectListItem() { Value = "Samoa", Text = "WS" },
        //    new SelectListItem() { Value = "San Marino", Text = "SM" },
        //    new SelectListItem() { Value = "Sao Tome and Principe", Text = "ST" },
        //    new SelectListItem() { Value = "Saudi Arabia", Text = "SA" },
        //    new SelectListItem() { Value = "Senegal", Text = "SN" },
        //    new SelectListItem() { Value = "Serbia", Text = "RS" },
        //    new SelectListItem() { Value = "Seychelles", Text = "SC" },
        //    new SelectListItem() { Value = "Sierra Leone", Text = "SL" },
        //    new SelectListItem() { Value = "Singapore", Text = "SG" },
        //    new SelectListItem() { Value = "Sint Maarten (Dutch part)", Text = "SX" },
        //    new SelectListItem() { Value = "Slovakia", Text = "SK" },
        //    new SelectListItem() { Value = "Slovenia", Text = "SI" },
        //    new SelectListItem() { Value = "Solomon Islands", Text = "SB" },
        //    new SelectListItem() { Value = "Somalia", Text = "SO" },
        //    new SelectListItem() { Value = "South Africa", Text = "ZA" },
        //    new SelectListItem() { Value = "South Georgia and the South Sandwich Islands", Text = "GS" },
        //    new SelectListItem() { Value = "South Sudan", Text = "SS" },
        //    new SelectListItem() { Value = "Spain", Text = "ES" },
        //    new SelectListItem() { Value = "Sri Lanka", Text = "LK" },
        //    new SelectListItem() { Value = "Sudan", Text = "SD" },
        //    new SelectListItem() { Value = "Suriname", Text = "SR" },
        //    new SelectListItem() { Value = "Svalbard and Jan Mayen", Text = "SJ" },
        //    new SelectListItem() { Value = "Sweden", Text = "SE" },
        //    new SelectListItem() { Value = "Switzerland", Text = "CH" },
        //    new SelectListItem() { Value = "Syrian Arab Republic", Text = "SY" },
        //    new SelectListItem() { Value = "Taiwan (Province of China)", Text = "TW" },
        //    new SelectListItem() { Value = "Tajikistan", Text = "TJ" },
        //    new SelectListItem() { Value = "Tanzania, United Republic", Text = "TZ" },
        //    new SelectListItem() { Value = "Thailand", Text = "TH" },
        //    new SelectListItem() { Value = "Timor-Leste", Text = "TL" },
        //    new SelectListItem() { Value = "Togo", Text = "TG" },
        //    new SelectListItem() { Value = "Tokelau", Text = "TK" },
        //    new SelectListItem() { Value = "Tonga", Text = "TO" },
        //    new SelectListItem() { Value = "Trinidad and Tobago", Text = "TT" },
        //    new SelectListItem() { Value = "Tunisia", Text = "TN" },
        //    new SelectListItem() { Value = "Turkey", Text = "TR" },
        //    new SelectListItem() { Value = "Turkmenistan", Text = "TM" },
        //    new SelectListItem() { Value = "Turks and Caicos Islands", Text = "TC" },
        //    new SelectListItem() { Value = "Tuvalu", Text = "TV" },
        //    new SelectListItem() { Value = "Uganda", Text = "UG" },
        //    new SelectListItem() { Value = "Ukraine", Text = "UA" },
        //    new SelectListItem() { Value = "United Arab Emirates", Text = "AE" },
        //    new SelectListItem() { Value = "United Kingdom of Great Britain and Northern Ireland", Text = "GB" },
        //    new SelectListItem() { Value = "United States Minor Outlying Islands", Text = "UM" },
        //    new SelectListItem() { Value = "United States of America", Text = "US" },
        //    new SelectListItem() { Value = "Uruguay", Text = "UY" },
        //    new SelectListItem() { Value = "Uzbekistan", Text = "UZ" },
        //    new SelectListItem() { Value = "Vanuatu", Text = "VU" },
        //    new SelectListItem() { Value = "Venezuela", Text = "VE" },
        //    new SelectListItem() { Value = "Viet Nam", Text = "VN" },
        //    new SelectListItem() { Value = "Virgin Islands (British)", Text = "VG" },
        //    new SelectListItem() { Value = "Virgin Islands (U.S.)", Text = "VI" },
        //    new SelectListItem() { Value = "Wallis and Futuna", Text = "WF" },
        //    new SelectListItem() { Value = "Western Sahara", Text = "EH" },
        //    new SelectListItem() { Value = "Yemen", Text = "YE" },
        //    new SelectListItem() { Value = "Zambia", Text = "ZM" },
        //    new SelectListItem() { Value = "Zimbabwe", Text = "ZW" },
        //    new SelectListItem() { Value = "Åland Islands", Text = "AX" },
        //};
    }
}
